# Generated by Django 5.2.13 on 2026-04-20 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ReservationDish',
        ),
    ]
