# Generated by Django 5.2.13 on 2026-04-22 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0002_delete_reservationdish'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='cancellation_reason',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='reservation',
            name='cancelled_by',
            field=models.CharField(blank=True, choices=[('client', 'Client'), ('restaurant', 'Restaurant')], max_length=20, null=True),
        ),
    ]
